// Auto-generated by OpenLane
module async_fifo(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input wclk,
  input wrst_n,
  input wen,
  input[7:0] wdata,
  output full,
  input rclk,
  input rrst_n,
  input ren,
  output[7:0] rdata,
  output empty
);
endmodule
